import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music Library Front Remake</title>
        <meta name="description" content="Generated by musicfrontremake" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Music Library
        </h1>

        <p className={styles.description}>
          Whats your jam?{' '}
          <code className={styles.code}>Where the music lives!</code>
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>!!! &rarr;</h2>
            <p>!!!</p>
          </a>

          <a href="" className={styles.card}>
            <h2>!!! &rarr;</h2>
            <p>!!!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>!!! &rarr;</h2>
            <p>!!!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>!!! &rarr;</h2>
            <p>
              !!!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.billboard.com/charts/hot-100/"
          target="_blank"
          rel="noopener noreferrer"
        >

          <span className={styles.logo}>
            <p>Current Billboard Top 100</p>
          </span>
        </a>
      </footer>
    </div>
  )
}
